replicaCount: 2

image:
  repository: aflorezg/parcial-arquitectura
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 8080

startupProbe:
  path: /api/pedido/generar-pedido
  port: 8080
  initialDelaySeconds: 25