replicaCount: 2

image:
  repository: aflorezg/parcial-arquitectura
  tag: 16bde2969a2cfe02bd30337c646fe39923ea07b5
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 8080

startupProbe:
  path: /api/pedido/generar-pedido
  port: 8080
  initialDelaySeconds: 25