apiVersion: apps/v1
kind: Deployment
metadata:
  name: pedido-micro-parcial
  labels:
    app: pedido-micro-parcial
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: pedido-micro-parcial
  template:
    metadata:
      labels:
        app: pedido-micro-parcial
    spec:
      containers:
        - name: pedido-micro-parcial
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          startupProbe:
            httpGet:
              path: {{ .Values.startupProbe.path }}
              port: {{ .Values.startupProbe.port }}
            initialDelaySeconds: {{ .Values.startupProbe.initialDelaySeconds }}