apiVersion: v1
kind: Service
metadata:
  name: pedido-micro-parcial
  labels:
    app: pedido-micro-parcial
spec:
  type: {{ .Values.service.type }}
  selector:
    app: pedido-micro-parcial
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}